### ISSUE TITLE
Attribute patterns are always generated even when not needed

### ISSUE THREAD

**Issue by DamianWiatrzyk** [alexanderrobitzsch/CDM#3]
There is in _din_ function attribute "skillclasses" which can reduce the number of used attribute profiles but function always generate all possible profiles and then check if we passed any profiles and overwrites generated. In case of working with a lot of attributes(for example over 100, which gives us 2^100 possible profiles) we have a number which can't be written as an integer which causes an error in _rep_ function. Also in case of passing attributes, we make unnecessary calculations.

I recommend first checking if user pass attributes profiles and if not then generate them.
For example: 
```
    # generate all attribute patterns                        

    attr.patt <- skillclasses

    if (is.null( skillclasses) ){
        attr.patt <- matrix( rep( 0, K*L), ncol=K)
        h1 <- 2
        if ( K >=2 ){
            for(ll in 1:(K-1) ){
                lk <- utils::combn( 1:K, ll )
                for ( jj in 1:( ncol(lk) ) ){
                    attr.patt[ h1, lk[,jj] ] <- 1
                    h1 <- h1 + 1
                }
            }
        }
    }
    
    L <- nrow(attr.patt)
```

**Comment by alexanderrobitzsch** [comment]
The issue is not the function you added but rather the internals inside the algorithm of the ``din`` function. The current implementation evaluates all 2^K skill classes (while setting some probabilities to zero if a user would request it). So, your proposal does not really resolve the issue that ``din`` in its current implementation is not suitable for many skills.
